'use client';

import { IconBrandAndroid, IconBrandAppleFilled } from '@tabler/icons-react';
import { format, isPast } from 'date-fns';
import Image from 'next/image';
import Link from 'next/link';
import * as React from 'react';

// import useAllProfiles from '@/hooks/use-all-profiles';
// import { useUpcomingDuties } from '@/hooks/use-upcoming-duties';
import { useOs } from '@repo/design-system//hooks/use-os';
import { Icons } from '@repo/design-system/components/icons';
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from '@repo/design-system/components/ui/avatar';
import { Badge } from '@repo/design-system/components/ui/badge';
import { Button } from '@repo/design-system/components/ui/button';
import { Card, CardContent } from '@repo/design-system/components/ui/card';
import type { CarouselApi } from '@repo/design-system/components/ui/carousel';
import {
  Carousel,
  CarouselContent,
  CarouselDots,
  CarouselItem,
} from '@repo/design-system/components/ui/carousel';
import { Progress } from '@repo/design-system/components/ui/progress';
import { Separator } from '@repo/design-system/components/ui/separator';
import { Skeleton } from '@repo/design-system/components/ui/skeleton';
import { useMediaQuery } from '@repo/design-system/hooks/use-media-query';

import { useSession } from '@repo/auth/client';
import type { User } from '@repo/auth/types';
import { getOrdinalSuffix } from '../../../lib/helper';
import type { Rosters } from '../../../lib/types';
import svgImage from '../../../public/undraw_happy_music_g6wc.svg';

export function DashboardOverview() {
  const os = useOs();
  const { data: session } = useSession();
  //   const { data: upcomingDuties } = useUpcomingDuties();
  const [indexOfUpcomingDate, setIndexOfUpcomingDate] = React.useState(0);
  const [api, setApi] = React.useState<CarouselApi>();
  const isMediumScreen = useMediaQuery('(min-width: 768px)');
  const isLargeScreen = useMediaQuery('(min-width: 1024px)');

  const profiles: User[] = [];
  const profile = session?.user;
  const upcomingDuties: Rosters[] = [];

  //   const onClickAddToCalendar = async () => {
  //     if (!upcomingDuties) {
  //       return;
  //     }

  //     const { atcb_action } = await import('add-to-calendar-button');

  //     const calendarConfig: ATCBActionEventConfig = {
  //       uid: '8b799eef-a589-497e-8c52-2046d2657d87',
  //       name: '[Reminder] Duty Roster',
  //       hideBranding: true,
  //       lightMode: 'bodyScheme',
  //       styleLight: '--modal-text-align: center',
  //       styleDark: '--modal-text-align: center',
  //       options: [os === 'ios' || os === 'macos' ? 'Apple' : 'Google'],
  //       dates: upcomingDuties.map((roster) => ({
  //         uid: `8b799eef-a589-497e-8c52-2046d2657d87-${roster.id}`,
  //         name: 'SAF Duty',
  //         description: `You have a duty on ${roster.duty_date} at 8am. Please be on time! This was automatically generated by the SAF Duty Roster at [url]${host}[/url].`,
  //         startDate: roster.duty_date,
  //       })),
  //       customLabels: {
  //         'modal.multidate.h': 'Google Calendar',
  //         'modal.multidate.text': 'Click on the dates to add to your calendar',
  //       },
  //     };

  //     // Trigger the Add to Calendar Button
  //     atcb_action(calendarConfig);
  //   };

  // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation>
  //   React.useEffect(() => {
  //     if (!api || !upcomingDuties) {
  //       return;
  //     }

  //     const index = upcomingDuties.findIndex((roster) => {
  //       return isFuture(roster.duty_date);
  //     });
  //     setIndexOfUpcomingDate(index);

  //     if (isLargeScreen) {
  //       api.scrollTo(Math.floor(index / 3));
  //     } else if (isMediumScreen) {
  //       api.scrollTo(Math.floor(index / 2));
  //     } else {
  //       api.scrollTo(index);
  //     }
  //   }, [api, upcomingDuties]);

  return (
    <>
      <div data-tour="home-page">
        <div className="flex w-full items-center space-y-2">
          <Avatar className="mr-3 inline-block h-10 w-10 items-center align-middle">
            <AvatarImage src={profile?.image ?? ''} className="object-cover" />
            <AvatarFallback>O</AvatarFallback>
          </Avatar>
          <h1 className="grow scroll-m-20 border-b pb-2 font-extrabold text-2xl tracking-tight sm:text-4xl lg:text-5xl">
            Howdy, {profile?.name ?? ''}
          </h1>
        </div>
        <p className="text-sm leading-7 sm:text-base [&:not(:first-child)]:mt-6">
          Review your upcoming duties and add them to your calendar. See who are
          on duty with you and get in touch with them.
        </p>
      </div>

      <div className="space-y-4">
        <div>
          <div className="mb-2 flex scroll-m-20 justify-between">
            <h4 className="font-semibold text-xl tracking-tight">
              Upcoming duties
            </h4>

            <Link
              href="/duty-roster"
              className="self-end font-light text-muted-foreground"
            >
              View all ➤
            </Link>
          </div>

          {upcomingDuties && upcomingDuties?.length > 0 ? (
            <>
              <Carousel
                className="relative grid w-full"
                setApi={setApi}
                opts={{
                  loop: true,
                  align: 'start',
                  slidesToScroll: 'auto',
                }}
              >
                <CarouselContent>
                  {upcomingDuties.map((roster, index) => (
                    <CarouselItem
                      key={roster.id}
                      className={
                        upcomingDuties.length !== 1
                          ? 'basis-5/6 md:basis-1/2 lg:basis-1/3'
                          : 'basis-full'
                      }
                    >
                      <div className="p-1">
                        <Card>
                          <CardContent className="flex h-[280px] flex-col justify-between p-6">
                            <div>
                              <div className="font-bold text-4xl">
                                {format(new Date(roster.dutyDate), 'd MMM')}
                              </div>
                              <div className="flex items-center align-middle font-semibold text-muted-foreground text-sm">
                                <Icons.clock className="mr-1 size-4" />
                                {format(new Date(roster.dutyDate), 'iii')} 8:00
                                AM
                              </div>
                              <div className="font-semibold text-muted-foreground text-red-600 text-xs">
                                {roster.isExtra && '🌚 [Extra]'}
                              </div>
                            </div>
                            <Badge variant="secondary" className="w-fit">
                              Your {getOrdinalSuffix(index + 1)} duty{' '}
                              {isPast(new Date(roster.dutyDate))
                                ? ' ✅'
                                : undefined}
                            </Badge>
                          </CardContent>
                        </Card>
                      </div>
                    </CarouselItem>
                  ))}
                </CarouselContent>
                <CarouselDots
                  dotsClassName="bg-primary w-4 h-1"
                  className="absolute right-0 bottom-4 left-0 z-10 my-0 flex h-1 flex-row justify-center"
                  gap="lg"
                />
              </Carousel>
              <Button
                variant="outline"
                // onClick={onClickAddToCalendar}
                className="mt-4 mr-auto ml-auto flex items-center rounded-full align-middle"
              >
                {os === 'ios' || os === 'macos' ? (
                  <IconBrandAppleFilled className="mr-1" />
                ) : (
                  <IconBrandAndroid className="mr-1" />
                )}
                Add to Calendar
              </Button>
            </>
          ) : (
            <div className="relative flex h-[342px] flex-col items-center justify-center">
              <Image
                priority
                src={svgImage}
                alt="Undraw personal information logo"
                className="h-48 object-contain sm:h-52"
              />
              <p className="pt-8 text-muted-foreground text-xl">
                No upcoming duties
              </p>
            </div>
          )}
        </div>

        <Separator />

        <div>
          <div className="mb-2 flex scroll-m-20 justify-between">
            <h4 className="font-semibold text-xl tracking-tight">
              Duties completed
            </h4>

            <p className="text-muted-foreground">
              {' '}
              {indexOfUpcomingDate === -1
                ? upcomingDuties?.length
                : indexOfUpcomingDate}{' '}
              of {upcomingDuties?.length || 0}
            </p>
          </div>

          <Progress
            value={
              upcomingDuties && upcomingDuties.length > 0
                ? indexOfUpcomingDate === -1
                  ? 100
                  : (indexOfUpcomingDate / upcomingDuties.length) * 100
                : 0
            }
            className="w-full"
          />
        </div>

        <Separator />

        <div>
          <h4 className="mb-2 scroll-m-20 font-semibold text-xl tracking-tight">
            Also on duty
          </h4>
          <Carousel
            className="!m-0 relative grid w-full"
            opts={{
              align: 'start',
              dragFree: true,
            }}
          >
            <CarouselContent>
              {profiles && profiles.length > 0
                ? profiles.map((profile) => (
                    <CarouselItem
                      key={profile.id}
                      className="flex basis-[21%] flex-col items-center justify-center border-none p-4 sm:basis-[11%]"
                    >
                      <Avatar>
                        <AvatarImage
                          className="rounded-xl object-cover"
                          src={profile.image || undefined}
                        />
                        <AvatarFallback>CN</AvatarFallback>
                      </Avatar>
                      <p className="py-2 text-center font-medium text-sm leading-none">
                        {profile.name}
                      </p>
                    </CarouselItem>
                  ))
                : Array.from({ length: 8 }).map((_, index) => (
                    <CarouselItem
                      key={index}
                      className="flex basis-[21%] flex-col items-center justify-center border-none p-2 sm:basis-[11%]"
                    >
                      <Skeleton className="h-12 w-12 rounded-full" />

                      <Skeleton className="mt-2 h-3 w-12" />
                    </CarouselItem>
                  ))}
            </CarouselContent>
          </Carousel>
        </div>
      </div>
    </>
  );
}
