// import { useEffect, useState } from 'react'
import dynamic from 'next/dynamic'
import {
  Container,
  createStyles,
  Divider,
  Text,
  Title,
  useMantineTheme,
  Box,
  Group,
  Flex,
  // LoadingOverlay,
  Paper,
  rem,
  Progress,
  Avatar,
  Stack,
  SimpleGrid,
  Skeleton,
} from '@mantine/core'
import { Carousel } from '@mantine/carousel'
import dayjs from 'dayjs'

import useUpcomingDuties from '@/hooks/useUpcomingDuties'
import { useSession } from 'next-auth/react'
import useUsers from '@/hooks/useUsers'
import Link from 'next/link'

const useStyles = createStyles((theme) => ({
  title: {
    fontFamily: `Greycliff CF, ${theme.fontFamily}`,
    color: theme.colorScheme === 'dark' ? theme.white : theme.black,
    lineHeight: 1,
    // [theme.fn.smallerThan('sm')]: {
    //   fontSize: rem(35),
    // },
  },

  titleWrapper: {
    display: 'flex',
    alignItems: 'center',
    '& > *:not(:last-child)': {
      marginRight: theme.spacing.sm,
    },
  },

  card: {
    height: rem(280),
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  },

  cardTitle: {
    fontFamily: `Greycliff CF, ${theme.fontFamily}`,
    fontWeight: 900,
    color: theme.colorScheme === 'dark' ? theme.white : theme.black,
    lineHeight: 1.2,
    fontSize: rem(32),
  },

  cardTime: {
    color: theme.colorScheme === 'dark' ? theme.white : theme.black,
    opacity: 0.7,
    fontWeight: 700,
    textTransform: 'uppercase',
    marginTop: theme.spacing.xs,
  },

  statsTitle: {
    fontWeight: 700,
    textTransform: 'uppercase',
  },

  statsValue: {
    fontSize: rem(15),
    fontWeight: 700,
    lineHeight: 1,
  },
}))

const AddToCalendarButton = dynamic(
  () => import('add-to-calendar-button-react').then((mod) => mod.AddToCalendarButton),
  {
    ssr: false,
  }
)

interface CardProps {
  title: string
  time: string
}

function Card({ title, time }: CardProps) {
  const { classes } = useStyles()

  return (
    <Paper
      shadow="md"
      p="xl"
      radius="md"
      // sx={{ background: getRandomGraidentStyle() }}
      className={classes.card}
    >
      <div>
        <Title order={3} className={classes.cardTitle}>
          {title}
        </Title>
        <Text className={classes.cardTime} size="xs">
          {time}
        </Text>
      </div>
      <Stack justify="flex-end" spacing="xs">
        <Title order={3}> Standby</Title>
        <Text size="md">Some other person</Text>
      </Stack>
    </Paper>
  )
}

UpcomingDutiesPage.title = 'Home'

export default function UpcomingDutiesPage() {
  const { data: session } = useSession()
  const { data: upcomingDuties, isLoading, error } = useUpcomingDuties()
  const { data: users, isLoading: userLoading } = useUsers()

  const { classes } = useStyles()
  const { colorScheme } = useMantineTheme()

  const calendarDates = upcomingDuties?.map((date) => ({
    name: 'SAF Duty',
    description: `You have a duty on ${date} at 8am, please be on time! This was automatically generated by the SAF Duty Roster.`,
    startDate: date,
  }))

  const data =
    upcomingDuties?.map((date) => ({
      title: dayjs(date).format('D MMM'),
      time: `${dayjs(date).format('ddd')} 8:00 AM`,
    })) || []

  const slides = data.map((item) => (
    <Carousel.Slide key={item.title}>
      <Card {...item} />
    </Carousel.Slide>
  ))

  // const [indexOfUpcomingDate, setIndexOfUpcomingDate] = useState(0)

  // useEffect(() => {
  //   setIndexOfUpcomingDate(
  //     upcomingDuties?.findIndex((date) => {
  //       const dutyDate = new Date(date)
  //       const today = new Date()

  //       return dutyDate.valueOf() > today.valueOf()
  //     }) || 0
  //   )
  // }, [upcomingDuties])

  if (error) {
    return (
      <Container my="xl" size="xl">
        <Text size="xl" color="red">
          {error.message}
        </Text>
      </Container>
    )
  }

  return (
    <Container my="xl" size="xl">
      <div className={classes.titleWrapper}>
        <Avatar src={session?.user?.image} radius="xl" />
        <Title className={classes.title}>Howdy, {session?.user?.name}</Title>
      </div>
      <Text color="dimmed" mt="md">
        Review your upcoming duties and add them to your calendar.
      </Text>
      <Divider my="sm" />
      <Group position="apart" mb="sm">
        <Title order={4}>Upcoming Duties</Title>
        <Text color="dimmed" component={Link} href="/duty-roster" prefetch={false}>
          View all ➤
        </Text>
      </Group>
      {upcomingDuties && upcomingDuties?.length > 0 ? (
        <>
          <Carousel
            loop
            withControls={false}
            withIndicators
            slideSize="50%"
            breakpoints={[{ maxWidth: 'sm', slideSize: '80%', slideGap: 'sm' }]}
            slideGap="xl"
            align="start"
            styles={{
              indicator: {
                width: rem(12),
                height: rem(4),
                transition: 'width 250ms ease',

                '&[data-active]': {
                  width: rem(40),
                },
              },
            }}
            slidesToScroll="auto"
          >
            {slides}
          </Carousel>

          <Group mt="md" position="center">
            <AddToCalendarButton
              name="Duty Roster"
              dates={calendarDates}
              hideCheckmark
              hideBackground
              buttonStyle="round"
              trigger="click"
              options={['Apple', 'Google']}
              lightMode={colorScheme}
              atcb-button-id="atcb-btn-1"
              atcb-last-event="initialization:atcb-btn-1"
              // @ts-expect-error Warning: Extra attributes from the server: class
              class={`atcb atcb-${colorScheme}`}
            />
          </Group>
        </>
      ) : (
        <Box my="xl">
          <Flex align="center" justify="center">
            <Text size="xl" color="dimmed">
              No upcoming duties
            </Text>
          </Flex>
        </Box>
      )}
      <Divider my="xl" />
      <Group position="apart" mb="sm">
        <Title order={4}>Duties Completed</Title>
        <Text color="dimmed" component="span">
          1 of 4
        </Text>
      </Group>
      <Progress mb="xl" value={50} size="lg" />
      <Divider my="xl" />
      <Title order={4} mb="sm">
        Duties Stats
      </Title>
      <SimpleGrid cols={3} breakpoints={[{ maxWidth: 'xs', cols: 1 }]}>
        <Paper withBorder p="md" radius="md">
          <Group position="apart">
            <Text size="xs" color="dimmed" className={classes.statsTitle}>
              Month
            </Text>
          </Group>

          <Group align="flex-end" mt={25}>
            <Text className={classes.statsValue}>50 duties worked this month</Text>
          </Group>
        </Paper>
        <Paper withBorder p="md" radius="md">
          <Group position="apart">
            <Text size="xs" color="dimmed" className={classes.statsTitle}>
              Year
            </Text>
          </Group>

          <Group align="flex-end" mt={25}>
            <Text className={classes.statsValue}>50 duties worked this month</Text>
          </Group>
        </Paper>
        <Paper withBorder p="md" radius="md">
          <Group position="apart">
            <Text size="xs" color="dimmed" className={classes.statsTitle}>
              Total
            </Text>
          </Group>

          <Group align="flex-end" mt={25}>
            <Text className={classes.statsValue}>50 duties worked this month</Text>
          </Group>
        </Paper>
      </SimpleGrid>
      <Divider my="xl" />
      <Title order={4} mb="sm">
        Also on duty
      </Title>
      <Carousel slideSize="10%" slideGap="sm" align="start" withControls={false} dragFree>
        {userLoading ? (
          <>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
            <Carousel.Slide>
              <Skeleton height={60} circle />
            </Carousel.Slide>
          </>
        ) : users && users.length > 0 ? (
          users?.map((user) => (
            <Carousel.Slide key={user.id}>
              <Avatar src={user.image} radius="xl" size="lg" />
              {user.name}
            </Carousel.Slide>
          ))
        ) : (
          <>
            <Text>No one else is on duty</Text>
          </>
        )}
      </Carousel>
    </Container>
  )
}
