import { defaultCache } from '@serwist/next/worker';
import type { PrecacheEntry, SerwistGlobalConfig } from 'serwist';
import { Serwist } from 'serwist';

import { name } from '@/lib/config';

// This declares the value of `injectionPoint` to TypeScript.
// `injectionPoint` is the string that will be replaced by the
// actual precache manifest. By default, this string is set to
// `"self.__SW_MANIFEST"`.
declare global {
  // eslint-disable-next-line unused-imports/no-unused-vars
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    // Change this attribute's name to your \`injectionPoint\`.
    // \`injectionPoint\` is an InjectManifest option.
    // See https://serwist.pages.dev/docs/build/inject-manifest/configuring
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  // A list of URLs that should be cached. Usually, you don't generate
  // this list yourself; rather, you'd rely on a Serwist build tool/your framework
  // to do it for you. In this example, it is generated by `@serwist/next`.
  precacheEntries: self.__SW_MANIFEST,
  // Whether the service worker should skip waiting and become the active one.
  skipWaiting: true,
  // Whether the service worker should claim any currently available clients.
  clientsClaim: true,
  // Whether navigation preloading should be used.
  navigationPreload: false,
  // Whether Serwist should log in development mode.
  disableDevLogs: true,
  // A list of runtime caching entries. When a request is made and its URL match
  // any of the entries, the response to it will be cached according to the matching
  // entry's `handler`. This does not apply to precached URLs.
  runtimeCaching: defaultCache,
});

self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json();
    const unreadCount = data?.unreadCount;

    const notificationPromise = self.registration.showNotification(
      data.title || name,
      {
        body: data.message || 'You have a new notification!',
        icon: '/icons/manifest-icon-192.maskable.png',
        badge: '/icons/manifest-icon-192.maskable.png',
      }
    );
    const promiseChain = [notificationPromise];

    // Check for support of the App Badging API
    if (navigator.setAppBadge) {
      if (unreadCount && unreadCount > 0) {
        promiseChain.push(navigator.setAppBadge(unreadCount));
      } else {
        promiseChain.push(navigator.clearAppBadge());
      }
    }

    event.waitUntil(Promise.all(promiseChain));
  }
});

self.addEventListener('notificationclick', (event) => {
  event?.notification.close();
  event?.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function (windowClients) {
        if (windowClients.length > 0) {
          let client = windowClients[0];
          for (let i = 0; i < windowClients.length; i++) {
            if (windowClients[i].focused) {
              client = windowClients[i];
            }
          }

          return client.focus();
        }

        return self.clients.openWindow('/');
      })
  );
});

serwist.addEventListeners();
