version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    network_mode: service:app
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    network_mode: service:app
    restart: unless-stopped

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    network_mode: service:app
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://localhost:6379"
      SRH_PORT: 8079
    depends_on:
      - redis

volumes:
  postgres-data:
