CREATE TABLE "notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"ord_date" date,
	"blockout_dates" date[],
	"max_blockouts" integer DEFAULT 8 NOT NULL,
	"weekday_points" integer DEFAULT 0 NOT NULL,
	"weekend_points" integer DEFAULT 0 NOT NULL,
	"no_of_extras" integer DEFAULT 0,
	"user_settings" jsonb DEFAULT '{"notify_on_duty_reminder":true,"notify_on_swap_requests":true,"notify_on_rosters_published":true}'::jsonb,
	CONSTRAINT "max_blockouts" CHECK (max_blockouts > 0)
);
--> statement-breakpoint
CREATE TABLE "push_subscriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "push_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"user_id" uuid NOT NULL,
	"push_subscription_details" jsonb NOT NULL,
	CONSTRAINT "push_subscriptions_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "rosters" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rosters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" uuid NOT NULL,
	"duty_date" date NOT NULL,
	"is_extra" boolean DEFAULT false NOT NULL,
	"duty_personnel_id" uuid,
	"reserve_duty_personnel_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "rosters_duty_date_unique" UNIQUE("duty_date")
);
--> statement-breakpoint
CREATE TABLE "swap_requests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swap_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"receiver_id" uuid NOT NULL,
	"requester_id" uuid NOT NULL,
	"reason" text,
	"organization_id" uuid NOT NULL,
	"receiver_roster_id" bigint NOT NULL,
	"requester_roster_id" bigint NOT NULL,
	CONSTRAINT "swap_requests_group_id_requester_id_receiver_roster_id_key" UNIQUE("requester_id","organization_id","receiver_roster_id"),
	CONSTRAINT "swap_requests_group_id_requester_id_requester_roster_id_key" UNIQUE("requester_id","organization_id","requester_roster_id")
);
--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ADD CONSTRAINT "push_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rosters" ADD CONSTRAINT "rosters_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rosters" ADD CONSTRAINT "rosters_duty_personnel_id_users_id_fk" FOREIGN KEY ("duty_personnel_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rosters" ADD CONSTRAINT "rosters_reserve_duty_personnel_id_users_id_fk" FOREIGN KEY ("reserve_duty_personnel_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_receiver_id_users_id_fk" FOREIGN KEY ("receiver_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_requester_id_users_id_fk" FOREIGN KEY ("requester_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_receiver_roster_id_rosters_id_fk" FOREIGN KEY ("receiver_roster_id") REFERENCES "public"."rosters"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "swap_requests" ADD CONSTRAINT "swap_requests_requester_roster_id_rosters_id_fk" FOREIGN KEY ("requester_roster_id") REFERENCES "public"."rosters"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "profiles_user_id_idx" ON "profiles" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "profiles_organization_id_idx" ON "profiles" USING btree ("organization_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "push_subscriptions_user_id_idx" ON "push_subscriptions" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "rosters_multi_idx" ON "rosters" USING btree ("organization_id" uuid_ops,"duty_personnel_id" uuid_ops,"reserve_duty_personnel_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "swap_requests_multi_idx" ON "swap_requests" USING btree ("organization_id" uuid_ops,"requester_id" uuid_ops,"receiver_id" uuid_ops,"receiver_roster_id" int8_ops,"requester_roster_id" int8_ops);